# Loki Configuration
# Purpose: Configures the log aggregation system
# Impact of removal: No log storage or querying capabilities

# Authentication settings
auth_enabled: false  # Disable authentication for development

# Server configuration
server:
  http_listen_port: 3100  # HTTP API port
  log_level: debug  # Logging verbosity level

# Common configuration for all components
common:
  path_prefix: /loki  # Base path for all Loki data
  storage:
    filesystem:
      chunks_directory: /loki/chunks  # Where to store log chunks
      rules_directory: /loki/rules  # Where to store recording rules
  replication_factor: 1  # Number of copies of each log chunk
  ring:
    kvstore:
      store: inmemory  # Use in-memory storage for ring

# Ingester configuration (handles log ingestion)
ingester:
  wal:
    enabled: true  # Enable Write-Ahead Logging
    dir: /loki/wal  # WAL directory
    replay_memory_ceiling: 2GB  # Maximum memory for WAL replay
  lifecycler:
    final_sleep: 0s  # How long to sleep before shutdown
  chunk_idle_period: 1h  # How long to keep chunks in memory
  max_chunk_age: 2h  # Maximum age of chunks
  chunk_retain_period: 1h  # How long to retain chunks after writing
  max_transfer_retries: 0  # Number of retries for chunk transfers

# Schema configuration for log storage
schema_config:
  configs:
    - from: 2020-05-15  # Start date for this schema
      store: boltdb-shipper  # Storage engine
      object_store: filesystem  # Where to store objects
      schema: v11  # Schema version
      index:
        prefix: index_  # Prefix for index files
        period: 24h  # How often to create new index files

# Storage configuration
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper/active  # Where to store active indices
    cache_location: /loki/boltdb-shipper/cache  # Where to store cache
    cache_ttl: 24h  # How long to keep cache entries
    shared_store: filesystem  # Shared storage backend
  filesystem:
    directory: /loki/chunks  # Where to store chunks

# Limits configuration
limits_config:
  enforce_metric_name: false  # Don't enforce metric names
  reject_old_samples: true  # Reject samples older than max_age
  reject_old_samples_max_age: 168h  # Maximum age of samples (7 days)

# Chunk store configuration
chunk_store_config:
  max_look_back_period: 0s  # How far back to look for chunks

# Table manager configuration
table_manager:
  retention_deletes_enabled: false  # Disable automatic deletion
  retention_period: 0s  # How long to retain data

# Compactor configuration
compactor:
  working_directory: /loki/compactor  # Where to store temporary files
  shared_store: filesystem  # Shared storage backend
