apiVersion: 1

contactPoints:
  - orgId: 1
    name: default
    receivers:
      - uid: email_default
        type: email
        settings:
          addresses: "admin@example.com"
        secureFields: {}
