# Prometheus Alert Rules Configuration
# Purpose: Defines conditions that trigger alerts when metrics exceed thresholds
# Impact of removal: No automated alerts for system issues

groups:
  - name: thinking_cluster  # Group name for organizing related alerts
    rules:

      # Loki availability alert
      # Purpose: Detects when Loki becomes unreachable
      # Impact of removal: No visibility into Loki's availability
      - alert: LokiDown
        expr: up{job="loki"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Loki is down"
          description: "Loki has been unreachable for more than 1 minute."

      # Promtail availability alert
      # Purpose: Detects when Promtail stops responding
      # Impact of removal: Log ingestion issues may go unnoticed
      - alert: PromtailDown
        expr: up{job="promtail"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Promtail is down"
          description: "Promtail has been unreachable for more than 1 minute."

      # Grafana availability alert
      # Purpose: Detects when Grafana UI is inaccessible
      # Impact of removal: Monitoring dashboards may be unavailable
      - alert: GrafanaDown
        expr: up{job="grafana"} == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Grafana is down"
          description: "Grafana has been unreachable for more than 1 minute."

      # Node exporter availability alert
      # Purpose: Detects if metrics collection from the WSL node fails
      # Impact of removal: No indication of infrastructure-level metrics
      - alert: NodeExporterDown
        expr: up{job="WSL_Machine"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Node Exporter on WSL is down"
          description: "Node Exporter instance {{ $labels.instance }} has been unreachable for more than 1 minute."

      # High CPU usage alert
      # Purpose: Detects when CPU usage is consistently high
      # Impact of removal: No warning about CPU overload
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80  # CPU usage > 80%
        for: 5m  # Must be high for 5 minutes before alerting
        labels:
          severity: warning  # Medium severity level
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% for 5 minutes."

      # High Disk usage alert
      # Purpose: Detects when disk space is running low
      # Impact of removal: No warning about disk space issues
      - alert: HighDiskUsage
        expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"}) > 85  # Disk usage > 85%
        for: 5m  # Must be high for 5 minutes before alerting
        labels:
          severity: warning  # Medium severity level
        annotations:
          summary: "High disk usage on {{ $labels.instance }}"
          description: "Disk usage is above 85% for 5 minutes."
