# Prometheus main configuration file
# Purpose: Defines how Prometheus collects metrics and manages alerts
# Impact of removal: Prometheus would not know what to scrape or how to handle alerts

global:
  scrape_interval: 5s  # How often to scrape targets - affects data granularity and resource usage

rule_files:
  - "alert_rules.yml"  # File containing alert rules

scrape_configs:
  # WSL Machine metrics collection
  # Purpose: Collects metrics from the WSL host machine
  # Impact of removal: No metrics from WSL machine
  - job_name: 'WSL_Machine'
    static_configs:
      - targets: ['the-thinking-cluster-node-exporter-1:9100']  # Node Exporter endpoint in WSL

  # Promtail service health check
  # Purpose: Detects if Promtail is down or unreachable
  # Impact of removal: No visibility into Promtail service health
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']  # Promtail metrics endpoint

  # Loki service health check
  # Purpose: Detects if Loki is down or not receiving logs
  # Impact of removal: No alerting if Loki becomes unresponsive
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']  # Loki API endpoint

  # Grafana service health check
  # Purpose: Detects if Grafana is down or not exposing dashboards
  # Impact of removal: No visibility into Grafana availability
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']  # Grafana API/metrics endpoint

