# Base bashrc configuration
# This file is version controlled and should contain common configurations

# Source local overrides if they exist
if [ -f ~/.bashrc.local ]; then
    source ~/.bashrc.local
fi

# Common aliases
alias ll='ls -la'
alias la='ls -A'
alias l='ls -CF'

# Common environment variables
export EDITOR=vim
export VISUAL=vim

# History settings
HISTSIZE=10000
HISTFILESIZE=20000
HISTCONTROL=ignoreboth:erasedups

# Append to history instead of overwriting
shopt -s histappend

# Check window size after each command
shopt -s checkwinsize

# Make less more friendly for non-text input files
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Set prompt
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# Add local bin to PATH if it exists
if [ -d "$HOME/.local/bin" ]; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Project-specific configurations
if [ -d "/mnt/d/documents/the-thinking-cluster" ]; then
    export THINKING_CLUSTER_ROOT="/mnt/d/documents/the-thinking-cluster"
    alias tcd="cd $THINKING_CLUSTER_ROOT"
fi
