# Expose metrics endpoint at port 9080
# Disable gRPC server. No need for it yet —— until we set up multi-node.
server:
  http_listen_port: 9080
  grpc_listen_port: 0
 
positions:
  filename: /home/gnsdud95/the-thinking-cluster/logs/promtail-positions.yaml

# Send logs to loki, at port 3100(Default loki port)
clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system_logs
          environment: wsl
          __path__: /home/gnsdud95/the-thinking-cluster/logs/system/*.log

  - job_name: crash_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: crash_logs
          environment: wsl
          __path__: /home/gnsdud95/the-thinking-cluster/logs/crashes/*.log

  - job_name: docker_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker_logs
          environment: wsl
          __path__: /var/lib/docker/containers/*/*.log

  - job_name: wsl_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: wsl_logs
          environment: wsl
          __path__: /var/log/wsl/*.log
